### ISSUE TITLE
gradle compile() error

### ISSUE THREAD

**Issue by ImanHosseini** [astrelsky/vscode-ghidra-skeleton#1]
* Where:
Script 'C:\ghidra_9.2.3\support\buildExtension.gradle' line: 51

* What went wrong:
A problem occurred evaluating script.
> Could not find method compile() for arguments [directory 'lib'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by astrelsky** [comment]
This is an issue with Ghidra and Gradle 7.0. Support for gradle 7 will come in the next major release of Ghidra and is currently available in the master branch. If you are using a public release of Ghidra you must use gradle 5 through 6.9
